/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package livrarias;

import javax.swing.table.DefaultTableModel;
import livrarias.DAO.autoresDAO;
import livrarias.DAO.editorasDAO;
import livrarias.DAO.livrosDAO;
import livrarias.classes.Autores;
import livrarias.classes.Editoras;
import livrarias.classes.Livros;

/**
 *
 * @author lethicia.favretto
 */
public class formLivros extends javax.swing.JFrame {

    /**
     * Creates new form formLivros
     */
    public formLivros() {
        initComponents();
        carregaDados();
        editorasDAO dao = new editorasDAO();

        for (Editoras e : dao.listar()) {
            cbEditora.addItem(e);
        }
        autoresDAO dao2 = new autoresDAO();
        for (Autores a : dao2.listar()) {
            cbAutor.addItem(a);

        }
    }

    public void carregaDados() {

        DefaultTableModel tabela = (DefaultTableModel) tLivros.getModel();
        tabela.setNumRows(0);
        livrosDAO dao = new livrosDAO();
        for (Livros l : dao.listar()) {
            tabela.addRow(new Object[]{
                l.getId_livros(),
                l.getEditora().getNome(),
                l.getAutor().getNome(),
                l.getTitulo(),
                l.getAno()
            });
        }
    }

    public void pesquisaDados() {

        DefaultTableModel tabela = (DefaultTableModel) tLivros.getModel();
        tabela.setNumRows(0);
        livrosDAO dao = new livrosDAO();
        for (Livros l : dao.pesquisar(tPesquisar.getText())) {
            tabela.addRow(new Object[]{
                l.getId_livros(),
                l.getEditora().getNome(),
                l.getAutor().getNome(),
                l.getTitulo(),
                l.getAno(),});
        }
    }

  
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        TLIVROS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfEditora = new javax.swing.JLabel();
        cbEditora = new javax.swing.JComboBox<>();
        tfTITULO = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        ANO = new javax.swing.JLabel();
        Ano = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tPesquisar = new javax.swing.JTextField();
        b = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tLivros = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tfAutor = new javax.swing.JLabel();
        cbAutor = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TLIVROS.setBorder(javax.swing.BorderFactory.createTitledBorder("                            Livros"));

        jLabel1.setText("Codigo:");

        tfEditora.setText("Editora:");

        tfTITULO.setText("Titulo:");

        ANO.setText("Ano:");

        Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPesquisarActionPerformed(evt);
            }
        });

        b.setText("Pesquisar");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        tLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "código", "editora", "autor", "titulo", "ano"
            }
        ));
        tLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLivrosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tLivros);

        tfAutor.setText("Autor:");

        jButton4.setText("Fechar");

        javax.swing.GroupLayout TLIVROSLayout = new javax.swing.GroupLayout(TLIVROS);
        TLIVROS.setLayout(TLIVROSLayout);
        TLIVROSLayout.setHorizontalGroup(
            TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TLIVROSLayout.createSequentialGroup()
                .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TLIVROSLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TLIVROSLayout.createSequentialGroup()
                                .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(TLIVROSLayout.createSequentialGroup()
                                .addComponent(tPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b))
                            .addGroup(TLIVROSLayout.createSequentialGroup()
                                .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(TLIVROSLayout.createSequentialGroup()
                                            .addGap(7, 7, 7)
                                            .addComponent(ANO))
                                        .addComponent(tfTITULO, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(tfAutor))
                                .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TLIVROSLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(TLIVROSLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(TLIVROSLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(TLIVROSLayout.createSequentialGroup()
                        .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TLIVROSLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jButton1)
                                .addGap(43, 43, 43)
                                .addComponent(jButton2)
                                .addGap(56, 56, 56)
                                .addComponent(jButton3)
                                .addGap(57, 57, 57)
                                .addComponent(jButton4))
                            .addGroup(TLIVROSLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        TLIVROSLayout.setVerticalGroup(
            TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TLIVROSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEditora)
                    .addComponent(cbEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TLIVROSLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TLIVROSLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAutor)
                            .addComponent(cbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTITULO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANO))
                .addGap(18, 18, 18)
                .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(33, 33, 33)
                .addGroup(TLIVROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TLIVROS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TLIVROS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Livros l = new Livros();
        livrosDAO DAO = new livrosDAO();

        Editoras editora = (Editoras) cbEditora.getSelectedItem();
        Autores autor = (Autores) cbAutor.getSelectedItem();

        l.setEditora(editora);
        l.setAutor(autor);
        l.setTitulo(tfTitulo.getText());
        l.setAno(Integer.parseInt(Ano.getText()));
        
        l.setId_livros(Integer.parseInt(tfCodigo.getText()));

        DAO.alterar(l);
        carregaDados();

        /*carregaDados();*/
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Livros l = new Livros();
        livrosDAO DAO = new livrosDAO();

        Editoras editora = (Editoras) cbEditora.getSelectedItem();
        Autores autor = (Autores) cbAutor.getSelectedItem();

        l.setEditora(editora);
        l.setAutor(autor);
        l.setTitulo(tfTitulo.getText());
        l.setAno(Integer.parseInt(Ano.getText()));

        DAO.cadastrar(l);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        pesquisaDados();
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Livros l = new Livros();
        livrosDAO DAO3 = new livrosDAO();

        l.setId_livros(Integer.parseInt(tfCodigo.getText()));

        DAO3.excluir(l);
        carregaDados();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLivrosMouseClicked
        String comboEditora = tLivros.getValueAt(tLivros.getSelectedRow(), 1).toString();
        for (int i = 0; i < cbEditora.getItemCount(); i++) {
            if (cbEditora.getItemAt(i).toString().equalsIgnoreCase(comboEditora)) {
                cbEditora.setSelectedIndex(i);

            }
        }
        String comboAutor = tLivros.getValueAt(tLivros.getSelectedRow(), 2).toString();
        for (int i = 0; i < cbAutor.getItemCount(); i++) {
            if (cbAutor.getItemAt(i).toString().equalsIgnoreCase(comboAutor)) {
                cbAutor.setSelectedIndex(i);
            }
        }

        tfCodigo.setText(tLivros.getValueAt(tLivros.getSelectedRow(), 0).toString());
        tfTitulo.setText(tLivros.getValueAt(tLivros.getSelectedRow(), 3).toString());
        Ano.setText(tLivros.getValueAt(tLivros.getSelectedRow(), 4).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_tLivrosMouseClicked

    private void tPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ANO;
    private javax.swing.JTextField Ano;
    private javax.swing.JPanel TLIVROS;
    private javax.swing.JButton b;
    private javax.swing.JComboBox<Object> cbAutor;
    private javax.swing.JComboBox<Object> cbEditora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tLivros;
    private javax.swing.JTextField tPesquisar;
    private javax.swing.JLabel tfAutor;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JLabel tfEditora;
    private javax.swing.JLabel tfTITULO;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
}
